src/pages/home/HomePage.tsx
src/pages/my/MyPage.tsx
src/pages/price/PricePage.tsx
src/router/Router.tsx
src/styles/index.tsx
src/styles/theme.ts

결제 화면 퍼블리싱
| 가격 화면 | 구독 화면 |
| - | - |
|<video src="https://github.com/user-attachments/assets/5ab92101-6698-4a08-9949-13682e195e5f" /> | <video src="https://github.com/user-attachments/assets/ea955e7a-1284-4388-81ad-a6e254034103" />|
1. 가격 화면 FAQ 영역 내용 필요
2. 연/월간 금액, 내용도 필요

[결제] 결제 화면 퍼블리싱

---

src/apis/queryClient.ts
src/components/price/Plan/Plan.tsx
src/hooks/mutations/payments/usePutPayments.tsx
src/pages/my/MyPage.tsx

- 구독 취소 API 연결
- 결제 전 로그인 여부 확인 로직 추가

[결제] 구독 취소 API 연결

---

src/components/Footer/Footer.tsx
src/layouts/Layout.tsx

- 발퍼블 죄송합니다 (일단 PG 심사 위해 급하게 작업)

Add: footer component

---

.github/CODEOWNERS
public/svg/ic_info-circle.svg
src/assets/svg/IcInfoCircle.tsx
src/assets/svg/index.ts
src/components/common/Button/Button.tsx
src/components/common/Input/Input.tsx
src/components/common/Text/Text.tsx
src/components/common/Textarea/Textarea.tsx
src/components/common/Toggle/Toggle.tsx
src/core/Prompt.ts
src/layouts/FooterLayout.tsx
src/pages/promptNew/components/FormItem.tsx
src/pages/promptNew/index.tsx
src/router/Router.tsx
src/styles/index.tsx
src/styles/theme.ts

-  프롬프트 추가 화면 퍼블리싱 
-  공통 컴포넌트 - Button, Text, Input, Textarea, Toggle 작업 
-  Select는 시간 부족하여 antd 컴포넌트 사용 (색상 토큰만 변경)
https://aea28932.pocket-prompt-frontend.pages.dev/prompt-new
| 프롬프트 추가 화면 |
| - | 
| ![image](https://github.com/user-attachments/assets/5476b845-a6ef-4b71-9777-ee03a160d66a) |
- theme.ts 에서 fonts를 조합으로 추가하였습니다 (이유: 초기에는 size, bold를 조합해서 사용하려 했으나 Text 컴포넌트를 추가하여 조합으로 사용하는 것이 깔끔할 것이라고 생각함) 
- 조합에서는 px 말고 rem 사용 (기기 폰트 사이즈 키운 경우, rem은 이를 반영함) 
**1️⃣ Text** 
| 사용 방법 |
| - |
|<img width="405" alt="image" src="https://github.com/user-attachments/assets/c0c0a748-4f80-4acb-975a-4376872823ad">| 
**2️⃣ Button**
| 기본 (primary) | secondary | normal | disabled |
| - | - | - | - |
|<video src="https://github.com/user-attachments/assets/335d84e5-020c-45f9-bc57-b86d9b56b170" />  | …

[프롬프트 추가] 화면 퍼블리싱

---

src/components/Header/Header.tsx

[헤더] pricing 탭 가리기

---

src/components/Header/Header.tsx

[헤더] pricing 탭 살리기

---

src/apis/prompt/prompt.model.ts
src/apis/prompt/prompt.ts
src/hooks/mutations/prompts/usePostPrompt.tsx
src/hooks/mutations/prompts/usePutPrompt.tsx
src/hooks/queries/prompts/usePromptQuery.tsx
src/hooks/queries/prompts/usePromptsListQuery.tsx
src/pages/home/components/Prompt/PaginatedPrompt.tsx
src/pages/promptNew/components/FormSection.tsx
src/pages/promptNew/index.tsx
src/router/Router.tsx

- 프롬프트 상세 조회 api 및 usePromptQuery 구현
- PromptNew 컴포넌트에서 수정 모드 구현
- 수정 모드일 경우 상세 조회 데이터로 초기 값 덮어씌움
- 수정 모드일 경우 수정 api 사용하도록 변경
- 프롬프트 생성시 visibility 소문자로 처리하도록 변경
- 이부분 토글 컴포넌트 수정이 필요해 보이는데, 시간이 부족해서 일단 api request시 소문자로 변경해서 넘겨주고 response 받은 부분은 대문자로 바꿔주도록 임시 처리했습니다 ㅠㅠ
- 익스텐션 연결 이후 첨부 예정

[프롬프트 수정] 수정 화면 구현 및 api 연결

---

src/router/Router.tsx

-   close #46
-   extension, pricing 페이지에만 footer 적용
https://github.com/user-attachments/assets/aee1e54d-0b7c-4069-b567-b80b4589ad1c

[푸터] extension, pricing 페이지에만 footer 적용

---

src/pages/extension/components/Extension8/styles.ts
src/pages/home/components/Prompt/PaginatedPrompt.tsx

-   홈화면 폰트 색 G_800으로 지정
-   익스텐션화면 배경색 white로 지정

[이슈] 다크모드시 홈화면 폰트 색상 및 extension 페이지 수정

---

src/core/Prompt.ts
src/core/UtmUri.ts
src/hooks/mutations/pocketRun/usePocketRun.tsx
src/pages/prompt/components/ExecuteSection.tsx
src/pages/prompt/components/PocketRunDropdown.tsx
src/pages/prompt/components/ResultSection.tsx

-  포켓런 결과란 입력값 토글로 변경
-  포켓런 실행시 기본 모델/ChatGPT로 분리 
- `Need Review` 포켓런 로직에 여러 기능들이 순차적으로 생기다보니 많이 더러워져서 코드 리팩토링이 필요한 것 같습니다 ㅠ 일단은 최대한 주석을 달아놓았어요.
- 402 에러별 (고급 모델 사용 에러, 횟수 소진 에러) 모달 기능 구현 
- AI 플랫폼 관련 상수 사용처별로 분리
- 프롬프트 생성 및 포켓런 실행시 동일한 상수를 사용하고 있었는데 위의 기획이 추가되면서 아래와 같이 사용하도록 바꾸었습니다!
- 프롬프트 생성시에는  기존처럼 ```const AIPlatforms = {ChatGPT: "ChatGPT", ...}```를 사용
- 포켓런 실행시에는 `const PocketRunModel = {ChatGPT: { label: "ChatGPT", value: "gpt-4o" }, ...}`을 사용 
https://github.com/user-attachments/assets/76dd62da-6738-44fc-80d9-3320edc7a413

[포켓런] 신규 기능 적용

---

index.html
package-lock.json
package.json
src/App.tsx
src/components/common/MetaTags/MetaTags.tsx
src/pages/prompt/index.tsx
yarn.lock

-   메타태그 react-helmet으로 관리하도록 변경

[SEO] React Helmet으로 메타태그 관리

---

src/apis/auth/auth.model.ts
src/pages/my/components/MyInfo.tsx

-   함께한 날, 실행한 프롬프트 정보 제공 기능 추가
-   반응형 디자인 이슈 해결
https://github.com/user-attachments/assets/c3d9ab97-fb51-4fba-a6c5-0e8b464370dc

[마이페이지] 추가 정보 제공 및 디자인 이슈 해결

---

src/pages/prompt/components/TopSection.tsx
src/pages/prompt/index.tsx

-  모바일 뷰 padding 조정
https://github.com/user-attachments/assets/d39389e9-cada-4bb9-a881-6a13ea3c1f2c

[프롬프트 상세] 모바일 뷰 padding 조정

---

src/components/LNB/LNB.tsx
src/pages/home/index.tsx
src/pages/my/index.tsx

-   LNB에 gtm 관련 속성 data-tracking-id 추가
- 홈: text-prompt, image-prompt, video-prompt, saved-prompt
- 마이페이지: my-page, my-subscription

[LNB] gtm 관련 속성 추가

---

amplify.yml
package.json

-   운영환경용 build:prod 추가
-   AWS amplify에 브랜치별 환경 변수 적용

[빌드] production 환경용 빌드 명령어 추가

---

amplify.yml
package.json

[빌드] 빌드 이슈 해결

---

ads.txt

chore : Google Adsense 세팅

---

.gitmodules
README.md
next.config.js
package.json

-   readme에 개발환경 주소 수정
-   env 네이밍 ...envs.v2 -> ...envs.next로 수정

[기타] 레포 통합에 맞춰 readme 및 env submodule 네이밍 수정

---

ads.txt
public/ads.txt

fix : file 위치 변경

---

src/app/layout.tsx

fix : head에 구글 애드센스 스크립트 추가

---

src/apis/client.ts
src/components/header/index.tsx
src/components/home/prompt/EmptyPrompt.tsx
src/components/lnb/index.tsx
src/components/prompt/ExecuteSection.tsx
src/components/prompt/PocketRunDropdown.tsx

-   포켓런 내용 바뀔 경우 버튼 string 바뀌지 않는 이슈
- 최초 실행시가 아니고 내용이 바뀔 경우 포켓런하기 -> 변경된 프롬프트로 실행하기 로 바뀌는 기획이 있어요!
-   프롬프트 둘러보기 버튼 라우트 이슈
-  잘못된 라우트 타고 있어서 변경했습니다.

[이슈] 프롬프트 둘러보기 버튼 라우트 이슈, 포켓런 내용 바뀔 경우 버튼 string 바뀌지 않는 이슈

---

src/app/layout.tsx
src/app/subscription/page.tsx
src/components/common/Input/Input.tsx
src/components/common/QnAToggle.tsx/QnAToggle.tsx
src/components/extension/Extension1/index.tsx
src/components/extension/Extension7/index.tsx
src/components/header/LoginButton.tsx
src/components/home/Banner.tsx
src/components/home/Search/SearchBar.tsx
src/components/home/Search/SearchChips.tsx
src/components/home/prompt/EmptyPrompt.tsx
src/components/home/prompt/PaginatedPrompt.tsx
src/components/lnb/HomeLnb.tsx
src/components/price/FAQ.tsx
src/components/price/plan/Plan.tsx
src/components/price/plan/PlanCard.tsx
src/components/prompt/ExecuteSection.tsx
src/components/prompt/PocketRunDropdown.tsx
src/components/prompt/ResultSection.tsx
src/components/promptNew/FormSection.tsx
src/components/sidebar/Item/GuideItem.tsx
src/components/sidebar/Item/MenuItem.tsx
src/components/sidebar/index.tsx

chore : gmt 세팅

---

src/apis/client.ts
src/app/layout.tsx
src/app/subscription/page.tsx
src/components/common/Input/Input.tsx
src/components/common/QnAToggle.tsx/QnAToggle.tsx
src/components/extension/Extension1/index.tsx
src/components/extension/Extension7/index.tsx
src/components/header/LoginButton.tsx
src/components/header/index.tsx
src/components/home/Banner.tsx
src/components/home/Search/SearchBar.tsx
src/components/home/Search/SearchChips.tsx
src/components/home/prompt/EmptyPrompt.tsx
src/components/home/prompt/PaginatedPrompt.tsx
src/components/lnb/HomeLnb.tsx
src/components/lnb/index.tsx
src/components/price/FAQ.tsx
src/components/price/plan/Plan.tsx
src/components/price/plan/PlanCard.tsx
src/components/prompt/ExecuteSection.tsx
src/components/prompt/PocketRunDropdown.tsx
src/components/prompt/ResultSection.tsx
src/components/promptNew/FormSection.tsx
src/components/sidebar/Item/GuideItem.tsx
src/components/sidebar/Item/MenuItem.tsx
src/components/sidebar/index.tsx
src/styles/GlobalStyle.ts

gmt 스크립트 추가
element id 추가 (btn, input 등)

25.02.13(1)

---

src/components/header/index.tsx

fix : id 누락 에러 수정

---

src/app/layout.tsx

fix : rm gmt script

---

src/app/layout.tsx
src/components/header/index.tsx

25.02.13(3)

---

src/components/lnb/HomeLnb.tsx

-   프롬프트 등록 버튼시 next/link만 사용하도록 수정
-   로그아웃일 때 버튼에 접근할 경우 이동하지 않고 로그인 유도 토스트 띄우도록 수정

[이슈] 로그아웃시 프롬프트 등록 접근할 수 없도록 수정

---

src/app/my/page.tsx
src/components/home/prompt/PaginatedPrompt.tsx
src/components/home/prompt/PromptBox.tsx

fix : 마이페이지 페이지네이션 오류 수정

---

public/svg/HomeVoc.tsx
src/app/page.tsx
src/components/home/VocModal.tsx
src/hooks/mutations/voc/usePostVoc.tsx

feat : voc 버튼 추가

---

src/components/extension/Extension9/index.tsx

fix : id 누락 수정

---

src/app/layout.tsx

fix : layout script 주석 제거

---

src/core/Prompt.ts

-   프롬프트 등록, 수정시 Perplexity 추가

feat: 프롬프트 등록, 수정시 Perplexity 추가

---

src/components/home/prompt/EmptyPrompt.tsx
src/components/lnb/HomeLnb.tsx
src/components/lnb/index.tsx
src/components/prompt/BookmarkButton.tsx
src/components/prompt/ExecuteSection.tsx
src/components/prompt/PocketRunDropdown.tsx
src/components/prompt/PromptTemplateModal.tsx
src/components/prompt/TopSection.tsx
src/components/promptNew/FormSection.tsx
src/core/Prompt.ts

Element ID 추가 요청 작업
- 프롬프트 템플릿 복사하기 "prompt-template-copy"
- 프롬프트 복사하기 "copy-prompt"
- 기본 모델 "based-pocket-run-toggle"
- ChatGPT "gpt-pocket-run-toggle"
- 저장한 프롬프트 "saved-prompt"
- 프롬프트 등록 "register-prompt"
- 프롬프트 즐겨찾기 한도 - 플랜 둘러보기 "saved-prompts-limit-explore-plans"
- 공유 버튼 "share-toggle"
- 저장 버튼 "saved-toggle"

feat : Element ID 추가 요청 작업

---

src/app/page.tsx
src/app/prompt/[promptId]/page.tsx
src/components/home/siderbarAd/DetailPageSiderBar.tsx
src/components/home/siderbarAd/HomeSiderBar.tsx

feat : 세로광고 추가

---

src/components/promptNew/index.tsx
src/hooks/mutations/prompts/usePostPrompt.tsx

-   프롬프트 입력값 초과시 detail 담은 모달 띄우도록 함
-   사용자 입력값 지워지지 않도록 수정
https://github.com/user-attachments/assets/f5678135-2cb5-40ca-82a5-eaee293c045d

[이슈] 프롬프트 입력값 30자 초과 에러 발생시 사용자 경험 개선

---

src/components/common/Textarea/Textarea.tsx

-   textArea 입력값에 따른 자동 높이 조절 기능 추가
-   isMini = true 일때만 적용
https://github.com/user-attachments/assets/67a834d1-3a6b-42eb-82cc-5b72f45fbc5c

[기능 추가] textArea 입력값에 따른 자동 높이 조절 기능 추가

---

src/components/common/Text/Text.tsx

-   Text 컴포넌트 pointer-event 감지되지 않도록 수정

[이슈] Text 컴포넌트 pointer-event 감지되지 않도록 수정

---

src/components/lnb/index.tsx

-   저장한 프롬프트 버튼 gtm 추적되지 않는 이슈

fix: 저장한 프롬프트 버튼 gtm 추적되지 않는 이슈

---

src/components/prompt/ExecuteSection.tsx

-   프롬프트 템플릿 확인하기 Text 클릭되지 않는 이슈

[이슈] 프롬프트 템플릿 확인하기 Text 클릭되지 않는 이슈

---

package.json
src/app/page.tsx
src/components/home/Search/SearchBar.tsx
src/components/home/Search/SearchChips.tsx
src/components/home/prompt/PaginatedPrompt.tsx
src/states/searchState.ts
src/states/sortState.ts
yarn.lock

- recoil-persist 라이브러리 설치
- 홈 검색 부분 초기화 로직 수정 및 세션 유지
- sort(인기순, 최신순 등) atom 파일 추가

[이슈]프롬프트 검색세션 유지

---

src/components/promptNew-v2/AiBox/AiRunBox.tsx
src/components/promptNew-v2/FormFirstSection.tsx
src/components/promptNew-v2/FormSecSection.tsx
src/components/promptNew-v2/index.tsx
src/hooks/mutations/prompts/useGetAiSuggestions.tsx

- prompt_template 데이터를 request body로 전달하도록 수정
- useGetAiSuggestions 훅에서 POST 요청을 수행하도록 변경

fix : GET에서 POST 요청 방식으로 변경

---

src/components/home/prompt/PromptListSection.tsx

-   isMobile일 때 Flex justify = 'center' 되도록 수정

[이슈] 홈화면 인기/추천 프롬프트 모바일 뷰일때 center justify 되도록 수정

---

src/components/promptNew-v2/AiBox/AiRunBox.tsx
src/components/promptNew-v2/FormSecSection.tsx
src/components/promptNew-v2/index.tsx

-   자동 생성된 제목/설명이 길어지면 줄바꿈
-   레이아웃 시프트 발생하는 부분 스타일 수정

fix : 줄바꿈 & 레이아웃 시프트 수정

---

.github/workflows/pr_preview.yml

-   preview 환경 삭제 job에서 AWS Credentials 정보들 with에 추가
-   불필요한 변수 선언 삭제하고 env로 대체

[이슈] preview 환경 삭제 job에서 AWS Credentials 참조되지 않는 에러 해결

---

README.md

[기타] Preview 기능 추가 관련 리드미 업데이트

---

src/components/common/ScrollButton/ScrollButton.tsx
src/components/home/prompt/PromptListSection.tsx
src/hooks/ui/useScrollButtonControl.tsx

-   모바일 뷰일 경우 가로 스크롤, 버튼 추가
-   가로 스크롤시 스크롤 포커스에 따라 다른 배경 색/외곽선 색 적용
-   스크롤 관련 제어 코드 useScrollButtonControl로 분리
https://github.com/user-attachments/assets/91c94db9-9c35-44c9-bb42-7eb28c55c744

[기능 추가] 인기/추천 프롬프트 모바일 뷰에서 가로 스크롤, 버튼 및 모션 기능 추가

---

src/components/sidebar/index.tsx

-   `<Link href="my">` -> `<Link href="/my">` 오타 수정

[이슈] 모바일에서 경로 중첩시 마이페이지로 이동하지 못하는 이슈

---

src/components/promptNew-v2/FormSecSection.tsx

-   title, description 값으로 isValid 교체

[이슈] 프롬프트 생성시 title, description 입력값에 따라 버튼 disabled 로직 추가

---

src/components/promptNew-v2/index.tsx

- 프롬프트 5개 이상 등록 시 err Modal 생성 
- "플랜 둘러보기" 버튼에 id 추가 (modal-price-button)

[기능추가]플랜 둘러보기 btn에 gmt id 추가

---

next.config.js
src/apis/prompt/prompt.model.ts
src/components/prompt/SampleImages.tsx
src/components/prompt/TopSection.tsx

-   프롬프트 정보 관련 ui 신규 디자인 반영
-   이미지 프롬프트일 경우 샘플 이미지 보여주는 기능 추가

[기능 추가] 프롬프트 상세 페이지 v2

---

src/components/home/prompt/PromptList.tsx
src/components/home/searchUI/SearchBar.tsx
src/states/sortState.ts

- 인기순, 최신순 sort 세션 유지하도록 수정
- 빌드 오류 수정

fix : 인기순, 최신순 sort 세션 유지

---

src/components/promptNew-v2/index.tsx

fix : 플랜 둘러보기 id 명 변경

---

src/components/promptNew-v2/index.tsx

- private_prompt_pricing_explore

fix : btn id명 수정

---

src/components/prompt/ExecuteSection.tsx
src/components/promptNew-v2/index.tsx

- private_prompt_pricing_explore -> private-prompts-limit-explore-plans
- modal-price-button -> advanced-model-explore-plans

fix : 찐 마지막 "플랜둘러보기" 버튼 gmt id 명 변경

---

src/apis/prompt/prompt.model.ts
src/components/home/prompt/PromptListSection.tsx

-    홈화면 메인 프롬프트 영역 이번주/이번달 top3 프롬프트로 변경

[수정] 홈화면 메인 프롬프트 영역 이번주/이번달 top3 프롬프트로 변경

---

src/app/page.tsx
src/app/subscription/page.tsx
src/components/home/HomeContent.tsx
src/components/home/banner/Banner.tsx
src/hooks/prefetches/usePrefetchPromptList.ts
src/hooks/prefetches/usePrefetchSubscription.ts
src/hooks/queries/payments/useGetSubscription.ts

-   /page.tsx에서 subscription prefetch
-   구독 정보를 조건부로 광고 컴포넌트 렌더링

[기능 추가] 구독자 대상 광고 제거 기능

---

src/components/prompt/ExecuteSection.tsx

[수정] 프롬프트 템플릿 조회시 인증 로직 추가

---

.github/workflows/discord-notify.yml

* Update discord-notify.yml
* Update discord-notify.yml

[Apply hotfix] Github Action Discord Notification (#195)

---

src/app/page.tsx
src/app/subscription/page.tsx
src/components/home/HomeContent.tsx
src/hooks/queries/payments/useGetSubscription.ts

-   로그인하지 않았을 경우에도 useGetSubscription 호출하여 401뜨고, 계속 호출함

[이슈] 로그인한 경우에만 useSubscription 호출하도록 변경

---

src/components/promptNew/index.tsx

fix : 프롬프트 토글 전환 숨김처리

---

next.config.js
src/apis/prompt/prompt.model.ts
src/components/prompt/EditDropdown.tsx
src/components/prompt/SampleImages.tsx
src/components/prompt/TopSection.tsx
src/components/promptNew/FormThirdSecion.tsx
src/components/promptNew/ImgUploadSection.tsx
src/components/promptNew/index.tsx
src/core/Prompt.tsx
src/hooks/mutations/prompts/usePostPrompt.tsx
src/hooks/mutations/prompts/useUploadMedia.tsx

- 이미지 프롬프트 일 때, 분야 카테고리 option 변경
- 이미지 프롬프트 수정하기 기능 추가
- 이미지 프롬프트 등록, 수정 모바일 뷰

feat : 이미지 프롬프트

---

src/components/promptNew/FormThirdSecion.tsx
src/components/promptNew/index.tsx
src/core/Prompt.tsx

-    DallE , Midjourney, Flux -> 옵션 추가

feat : 이미지 프롬프트용 ai 옵션 추가

---

src/components/promptNew/FormSecSection.tsx
src/components/promptNew/ImgUploadSection.tsx
src/components/promptNew/index.tsx

-   텍스트 프롬프트 , 이미지 프롬프트 스타일 통일감있도록 수정
-   토글 변경 시 폼 초기화 로직 수정

fix : 토글 전환 초기화 & 스타일 통일

---

next.config.js

---
name: Pull Request Template
about: PR 생성용 템플릿
title: "[이슈번호] 작업 내용"
labels: ""
assignees: ""
---
-   close #
-   [ ]
-   [ ]

[기타] 이미지 호스팅용 s3 bucket hostname 추가

---

src/components/home/prompt/list/PromptListSectionBase.tsx

fix : 정렬 초기화 기준 변경

---

src/components/home/prompt/PromptList.tsx
src/components/home/prompt/list/PromptListSectionImage.tsx
src/components/home/prompt/list/PromptListSectionText.tsx
src/hooks/queries/prompts/usePromptsListQuery.tsx

fix : 주간, 월간 프롬프트 중복 제거

---

src/apis/prompt/prompt.model.ts
src/components/home/prompt/PromptList.tsx

- 마이페이지 private, public 카운트 오류 수정 완료

fix : 마이페이지 count 오류 수정

---

src/components/home/prompt/card/PromptCardImage.tsx
src/components/promptNew/ImgUploadSection.tsx
src/components/promptNew/index.tsx

-  이미지 삭제 로직 추가
-  대표 썸네일 로직 추가

fix : 이미지 프롬프트 qa 1차 수정

---

src/components/price/plan/Plan.tsx

[이슈] Plan 컴포넌트 빌드 이슈 해결

---

src/components/prompt/PocketRunDropdown.tsx
src/core/Prompt.tsx

-   텍스트 포켓런 모델 추가 (claude, perplexity)
-   신규 모델에 new 표시 추가

[기능 추가] 텍스트 포켓런 모델 추가 (claude, perplexity)

---

src/components/price/plan/PlanCard.tsx
src/components/price/plan/PlanData.ts

[기타] pricing 페이지 plan 최종 변경

---

src/components/home/prompt/card/PromptCardImage.tsx
src/components/prompt/SampleImages.tsx
src/core/Banner.ts

-  이미지 미리보기 기능 추가 (이미지 로드 시간이 좀 걸려서 프로그래스 추가 고민)
-  이미지 컴포넌트 높이 조절
- 이미지 배너 링크 수정

feat : 이미지 미리보기 추가 + 높이 조절

---

src/components/home/prompt/card/PromptPopularCardImage.tsx
src/components/home/prompt/list/PromptListSection.tsx

fix : 주간, 월간 매핑 수정

---

src/app/my/page.tsx
src/components/prompt/ExecuteSection.tsx
src/components/prompt/ResultSection.tsx

- 이미지 포켓럿 url 출력 -> 이미지 출력 수정
- 마이페이지 마운트 로직 수정

fix : 이미지 포켓런 결과 수정

---

next.config.js
src/components/prompt/ResultSection.tsx
src/core/Prompt.tsx

-   이미지 상세 보기 기능 추가
-   dall e 추가

feat : 이미지 포켓런 상세수정

---

src/app/saved-prompt/page.tsx
src/components/home/prompt/list/PromptList.tsx
src/components/home/prompt/list/PromptListSection.tsx
src/hooks/queries/useSearch.tsx
src/hooks/ui/usePromptList.tsx

-   저장된 프롬프트 페이지 피그마 참고 퍼블리싱 및 검색 로직 적용

feat : 저장된 프롬프트 ui 및 검색 적용

---

.eslintrc.json
src/app/sitemap.ts
src/hooks/queries/useSearch.tsx

This pull request includes updates to improve code quality, functionality, and consistency across the project. The most notable changes include enhancements to the sitemap generation logic, updates to ESLint configuration for better linting, and simplifications in the search hook logic.
* Refactored the `fetchPrompts` function in `src/app/sitemap.ts` to implement paginated fetching with a limit and maximum pages, improving efficiency and handling errors gracefully.
* Updated the sitemap generation logic to ensure proper formatting, error handling, and consistent coding style.
* Added `next/core-web-vitals` and `next/typescript` to `.eslintrc.json` to enforce better linting rules and TypeScript standards.
* Simplified the `useSearch` hook in `src/hooks/queries/useSearch.tsx` by removing …

Hotfix: Codex/fix/search update

---

src/app/layout.tsx

-   </body> 앞에 Naver Analytics 태그를 추가했습니다.

feat: Naver Analytics 태그 추가

---

src/app/layout.tsx

-   naver analytics 제거
-   naver search advisor 등록

chore: Naver search advisor 등록

---

src/app/layout.tsx

-   chore: Naver search advisor 등록 (#268)

25.07.14 (2)
