ai-surfers/pocket-prompt-frontend

- src/hooks/queries/prompts/usePromptQuery.tsx
- 카테고리 전환 이슈 해결
- queryKey에 카테고리 포함되어 있지 않아 발생
- api Request에 category 바뀌는 부분 확인 가능 / 다만 백에서 같은 response 반환중
> fix: 카테고리 전환 이슈 해결

- src/apis/prompt/prompt.model.ts
- src/hooks/queries/prompts/usePromptQuery.tsx
-   프롬프트 리스트 조회시 categories에 단일 문자열 전달하도록 수정
ex. `/prompts-list?...categories=writing`
> [홈] 프롬프트 리스트 조회시 categories에 단일 문자열 전달하도록 수정

- src/apis/prompt/prompt.model.ts
- src/apis/prompt/prompt.ts
- src/hooks/mutations/prompts/usePostPrompt.tsx
- src/hooks/mutations/prompts/usePutPrompt.tsx
- src/hooks/queries/QueryKeys.ts
- src/hooks/queries/prompts/usePromptQuery.tsx
- src/hooks/queries/prompts/usePromptsListQuery.tsx
- src/pages/home/components/Prompt/PaginatedPrompt.tsx
- src/pages/promptNew/components/FormSection.tsx
- src/pages/promptNew/index.tsx
- src/router/Router.tsx
[해당 PR ](https://github.com/ai-surfers/pocket-prompt-frontend/pull/36)정상적으로 머지되지 않아 다시 PR 올립니다
- 프롬프트 상세 조회 api 및 usePromptQuery 구현
- PromptNew 컴포넌트에서 수정 모드 구현
- 수정 모드일 경우 상세 조회 데이터로 초기 값 덮어씌움
- 수정 모드일 경우 수정 api 사용하도록 변경
- 프롬프트 생성시 visibility 소문자로 처리하도록 변경
- 이부분 토글 컴포넌트 수정이 필요해 보이는데, 시간이 부족해서 일단 api request시 소문자로 변경해서 넘겨주고 response 받은 부분은 대문자로 바꿔주도록 임시 처리했습니다 ㅠㅠ
- 익스텐션 연결 이후 첨부 예정
> [프롬프트 수정] 수정 화면 구현 및 api 연결 2

- src/apis/client.ts
- web/extension 로깅 구분을 위한 목적으로 헤더에 `source-location: web`을 추가했습니다
- 전체 요청 시에 헤더에 보내기로 이야기되어서 여기에 추가했어요
> [기타] API 헤더에 source-location 추가

- src/pages/home/components/Prompt/Prompt.tsx
- src/pages/prompt/components/ExecuteSection.tsx
- src/pages/prompt/components/PocketRunDropdown.tsx
- src/pages/prompt/components/ResultSection.tsx
- src/pages/prompt/index.tsx
- src/states/pocketRunState.ts
- 포켓런 로딩 동작 구현
- 최초 포켓런 이후 입력값 변경시 버튼 string 수정
- 최초 포켓런시: 포켓런 하기
- 최초 포켓런 이후 입력값이 변경되었을 경우: 변경된 프롬프트로 다시 실행하기 
- `Need Review` form watch와 useRef 사용해서 입력값을 비교했는데 더 간결한 방법이 있을까요?
- 프롬프트 상세 페이지 접근시 포켓련 결과 상태 초기화
- 포켓런 실행해서 저장해둔 상태가 있을 경우 다른 프롬프트로 이동시 해당 상태가 렌더링되는 이슈 방지
- `Need Review` 프롬프트 onClick 이벤트 발생시 걸어두었는데 다른 루트로 프롬프트 상세 페이지 접근 가능성이 있을까요? 
- 결과 복사 버튼 구현
- 기획팀에 확인 결과 복사 성공시 toast 버튼이 나와야 한다고 합니다! 요부분 세부 디자인 요청해놓은 상태로 다음 스프린트때 일괄 수정해놓을게용 
https://github.com/user-attachments/assets/07b59575-f358-4dd1-bb95-2fe9ca45083c
> [프롬프트 상세] 포켓런 부가 기능

- package.json
- src/assets/svg/home/Close.tsx
- src/components/Header/Header.tsx
- src/components/Header/LoginButton/LoginButton.tsx
- src/components/Sidebar/Item/GuideItem.tsx
- src/components/Sidebar/Item/MenuItem.tsx
- src/components/Sidebar/Sidebar.tsx
- src/core/Menu.ts
- src/layouts/FooterLayout.tsx
- src/layouts/Layout.tsx
- src/router/Router.tsx
- 모바일 헤더를 위한 사이드바를 구현하였습니다 
- 작업하면서 layout도 `Layout.tsx`를 기본으로 사용하고, Footer 필요한 것들은 한번 더 감싸도록 수정하였습니다 (기존에는 각 레이아웃 따로 사용함) 
- 메뉴도 상수로 분리해두었습니다 
| 모바일 |
| - |
|<video src="https://github.com/user-attachments/assets/eab85b86-be77-45f5-984a-f9eec6b7c367"/> |
> [사이드바] 모바일 헤더 사이드바구현 

- src/components/Header/GuideButton/GuideButton.tsx
- src/components/Header/Header.tsx
- src/components/Header/LoginButton/LoginButton.tsx
- src/components/Header/LogoutButton/LogoutButton.tsx
- src/components/Header/User/User.tsx
- src/components/Sidebar/Sidebar.tsx
-   [사이드바]
- 로그인 상태 추가
-   [헤더]
- 가이드 버튼 추가
- 최대 넓이 1440Px로 수정
- 사이드바 로그인 상태 추가
https://github.com/user-attachments/assets/8787119b-3726-45ec-aa1d-3811c11d4b5c
- 헤더 가이드 버튼 추가 및 넓이 수정
> [사이드바, 헤더] 로그인 상태 및 가이드 버튼 추가

- src/components/Header/User/User.tsx
- src/components/common/Text/Text.tsx
- src/pages/prompt/index.tsx
-   포켓런 실행/결과란 높이 이슈
- 실행란 및 결과란이 같은 높이로 적용되어 결과가 길어질 경우 실행란도 길어지는 이슈
- height: fit-content해서 내용에 맞는 높이로 적용
-   코드블록 overflow 이슈
- 포켓런 결과란에 표시되는 코드블럭이 길어질 경우 줄바꿈되지 않는 이슈
- overflow 관련 적용
- 이외에 보다 chat GPT와 유사하도록 폰트 수정 
- 헤더 유저 버튼에 hover, selected 상태 추가
https://github.com/user-attachments/assets/fe949a99-02d3-4a1a-a277-b97181c4f935
https://github.com/user-attachments/assets/48764ef7-3ff4-404b-8fbc-9c0b4fa644a2
> [이슈 해결] 포켓런 실행/결과란 높이 이슈, 코드블록 overflow 이슈, 헤더 유저 버튼 hover, selected 추가

- src/styles/GlobalStyle.ts
-   애드센스가 추가될 때 `height: auto !important; min-height: 0px !important;` 가 자동으로 붙는 것 같아요.
레이아웃이 중앙에 배치되는 이슈가 있어서 globalStyle 수정해두었습니다.
-   이슈 발생 모습
> [이슈] 애드센스 추가되어 발생한 레이아웃 이슈 수정

- src/app/page.tsx
-   `⨯ useSearchParams() should be wrapped in a suspense boundary at page "/".`
-   useSearchParams 는 클라이언트에서만 실행되어야 하는데, 직접 참조되는 코드가 있어서 이슈 발생
-   useMemo나 useEffect로 감싸면 클라이언트에서만 실행되도록 보장
> [이슈] useSearchParams Suspense 경고 해결

- src/app/page.tsx
-   `⨯ useSearchParams() should be wrapped in a suspense boundary at page "/".`
-   useSearchParams 는 클라이언트에서만 실행되어야 하는데, 직접 참조되는 코드가 있어서 이슈 발생
-   useEffect로 감싸면 클라이언트에서만 실행되도록 보장
> [이슈] useEffect로 useSearchParams Suspense 오류 해결하도록 변경

- src/app/page.tsx
-    `⨯ useSearchParams() should be wrapped in a suspense boundary at page "/".`
-    useSearchParams는 클라이언트에서만 실행되어야 하며, SSR 방지를 위해 Suspense로 감싸야 함
-    Suspense 사용시 데이터 로드까지 fallback 띄우므로 렌더링 속도 느려질 가능성 있음
-    다만 현재 코드에서는 이미 hydration 에러 방지를 위해 초기 렌더링을 막고 있어서 추가
https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
> [이슈] useSearchParams 사용시 Suspense로 감싸도록 변경

- src/app/layout.tsx
- 기존 dangerouslySetInnerHTML 방식 대신 Next.js의 <Script> 컴포넌트 사용
- Google Tag Manager 및 외부 스크립트 로드 최적화 적용
- 코드 보안 및 유지보수성 향상
> fix : 스크립트 로드 방식 개선

- src/components/prompt/BookmarkButton.tsx
- src/components/prompt/TopSection.tsx
-   as-is
-   즐겨찾기 버튼이 아닌 즐겨찾기 컴포넌트에 gtm Id 설정되어 gtm 추적 불가
-   즐겨찾기 컴포넌트에 전달되어야 하는 prompt Id가 gtm id로 변경되어 즐겨찾기 api 쿼리스트링에 잘못된 값 전달됨
-   to-be
-   즐겨찾기 버튼 자체에 gtm id 지정하도록 변경
-   즐겨찾기 컴포넌트에는 기존대로 promptId 전달하도록 변경
-   기능 추가
-   즐겨찾기 완료 / 즐겨찾기 해제 완료시 토스트 추가
- 즐겨찾기: '프롬프트가 즐겨찾기 되었어요.'
- 해제: '프롬프트 즐겨찾기가 해제되었어요.'
> [이슈] 즐겨찾기 버튼 id와 api 요청 로직 분리 및 즐겨찾기 토스트 추가

- src/components/common/Icon.tsx
- src/components/lnb/index.tsx
-   발생 원인
-   Icon 컴포넌트가 point-event 가로채서 버튼으로 click 이벤트 발생하지 않음
-   컴포넌트에 id만 전달되고 element에 id 지정되지 않음
-   Todo: next/link와 Button 컴포넌트가 같이 쓰이는 코드 수정해야 함
-   next/link가 내부적으로 a태그를 사용하기 때문에,  a태그안에 button 태그 들어가있게 됨
-   웹표준에 맞지 않고 사이드이펙트 발생 우려
> [이슈] gtm 인식 안되는 이슈 해결

- src/components/home/prompt/PaginatedPromptSection.tsx
-   검색어 입력 후 저장한 프롬프트 화면으로 이동시 검색 결과 프롬프트 리스트가 렌더링됨
-   검색어 세션 유지 기능 추가되면서 프롬프트 리스트를 조건부 렌더링 로직 수정 필요
-   현재 pathname이 홈 화면에 해당할 때 검색 결과 렌더링되도록 수정
- 수정 전 이슈 화면
> [이슈] 검색 결과가 저장된 프롬프트 화면에 렌더링되는 이슈

- src/components/common/Text/Text.tsx
-   이슈 원인
-   저장한 프롬프트 gtm 추적시 click element가 text 컴포넌트로 잡혔던 히스토리
-   상기 이슈 해결을 위해 text 컴포넌트의 Pointer-events 해제해놓음
-   다만 특정 드롭다운에서 button을 넣지 않고 text 컴포넌트에 직접 Onclick 이벤트 할당해서 생긴 문제
-  해결
-   onclick 이벤트 전달시 pointer-events 허용으로 변경
> [이슈] text 컴포넌트에 onClick 이벤트 전달될 경우 pointer-events 허용

- src/components/promptNew-v2/index.tsx
-   원인: <form onSubmit={handleClickSubmit}가 부모, 자식 컴포넌트 모두 감싸고 있어 중복 실행됨
-   해결:  form 태그 중복 제거
> [이슈] handleSubmit 중첩되어 프롬프트 두 번 생성되는 이슈 해결

- src/components/promptNew-v2/index.tsx
- src/hooks/queries/useInvalidateQueryKeys.tsx
-   캐싱된 서버 상태를 무효화해야 할 경우 사용할 수 있는 useInvalidateQueryKeys 추가
-   예시) 프롬프트 수정시 해당 Query Key(프롬프트 id)로 캐싱된 프롬프트 detail 값 무효화
> [기능 추가] Query key 무효화하는 hooks 추가

- src/app/extension/page.tsx
- src/app/my/page.tsx
- src/app/price/page.tsx
- src/app/saved-prompt/page.tsx
- src/components/home/HomeContent.tsx
- src/components/home/prompt/PromptList.tsx
- src/components/home/searchUI/SearchBar.tsx
- src/components/home/searchUI/SearchChips.tsx
- src/hooks/queries/prompts/usePromptsListQuery.tsx
- src/states/searchState.ts
- 프롬프트 상세 페이지 들어갔다가 뒤로가기 했을 때 검색유지
- 프롬프트 상세가 아닌 다른 페이지, 홈 로고 클릭했을 때, 새로고침 했을 때 검색 초기화
(현재 next 14버전을 사용하면서 상위 레이아웃이 공유되어 있는 구조가 잘못된 듯 합니다.)
(최대한 구조 변경없이 수정해보았습니다. 다른 사이드 이펙트가 나오면 공유 부탁드립니다!)
> fix : search 버그 수정

- src/components/home/prompt/PromptListSection.tsx
- 분기 조건에 viewType 검사를 추가함
- 검색 상태가 홈 화면("open")에서만 영향을 미치고, 다른 탭에는 영향을 주지 않도록 코드를 수정
> fix : 검색 쿼리 조건문 수정

- src/app/prompt/[promptType]/[promptId]/page.tsx
- src/middleware.ts
-   src/middleware.ts 추가 
-  응답의 `type`(text | image) 값에 따라 `/prompt/{type}/{id}` 로 307 Redirect
- ID가 유효하지 않으면 404 페이지로 리라이트
1. `GET /prompt` → `/prompt/text`  
2. `GET /prompt/{24hexID}` → middleware → `/prompt/{type}/{id}`  
3. `/prompt/text/...`, `/prompt/image/...` → 기존 컴포넌트 정상 렌더링
> fix : 경로 리다이렉트

- src/components/common/Input/Input.tsx
This pull request introduces a small but important enhancement to the `Input` component in `src/components/common/Input/Input.tsx`. The change adds IME (Input Method Editor) composition awareness to the `handleKeyDown` function, ensuring that the `Enter` key behavior does not interfere with ongoing text composition.
> fix: trigger search on Enter when using IME
